# ARRAYS (1D,2D,3D)

In [51]:
import numpy as np

In [3]:
A1=np.array([1,2,3,4])

In [5]:
print(A1)

[1 2 3 4]


In [7]:
type(A1)

numpy.ndarray

In [9]:
A1.shape

(4,)

In [11]:
A1.size

4

In [15]:
A2=np.array([[1,2,3,4],[5,6,7,8]])

In [17]:
print(A2)

[[1 2 3 4]
 [5 6 7 8]]


In [25]:
A2.ndim  #to check dimension 

2

In [21]:
A2.shape

(2, 4)

In [23]:
A2.size

8

In [33]:
A3=np.array([[[1,2],[3,4],[5,6]]])

In [41]:
A3.size
A3.shape
A3.ndim

3

In [45]:

print(A3)

[[[1 2]
  [3 4]
  [5 6]]]


# Zero Array

an array in which all values are 0

## ZA=np.zeros(shape,dtype)

In [54]:
import numpy as np

In [58]:
z1=np.zeros(3)
z1

array([0., 0., 0.])

In [64]:
z1=np.zeros(30,dtype=int)
z1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [70]:
type(z1)
np.ndim(z1)

1

In [72]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [76]:
z2=np.zeros((3,4),dtype=int)
z2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [78]:
z2.shape

(3, 4)

In [82]:
z3=np.zeros((2,3,4))
z3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [84]:
z3.ndim

3

In [90]:
z3.size

24

In [92]:
z3.shape

(2, 3, 4)

# ones array

all values are one 

## A=np.ones(shape,dtype)

In [96]:
import numpy as np

In [100]:
a1=np.ones(8)
print(a1)

[1. 1. 1. 1. 1. 1. 1. 1.]


In [104]:
a1=np.ones(3,dtype=int)
print(a1)

[1 1 1]


In [106]:
type(a1)

numpy.ndarray

In [108]:
a1.ndim

1

In [110]:
a1.size

3

In [112]:
a1.shape

(3,)

In [116]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [118]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [120]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [126]:
np.ones((3,6),dtype=int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [130]:
a3=np.ones((2,4,6))
print(a3)

[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]


In [132]:
a3=np.ones((2,4,6),dtype=int)
print(a3)

[[[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]

 [[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]]


In [134]:
np.ndim(a3)

3

In [138]:
a3.size


48

# Full Array

## F=np.full(shape,fill_value)

In [142]:
import numpy as np

In [150]:
f1=np.full(6,45)

In [152]:
print(f1)

[45 45 45 45 45 45]


In [156]:
f1=np.full(3,45,dtype=float)
print(f1)

[45. 45. 45.]


In [158]:
f1=np.full(3,45,dtype=int)
print(f1)

[45 45 45]


In [160]:
type(f1)

numpy.ndarray

In [164]:
f1.ndim

1

In [168]:
f2=np.full((2,3),53.4)
print(f2)

[[53.4 53.4 53.4]
 [53.4 53.4 53.4]]


In [172]:
f2=np.full((2,3),34.8,dtype=int)
print(f2)

[[34 34 34]
 [34 34 34]]


In [176]:
f3=np.full((2,3),23.4,dtype=str)
print(f3)

[['2' '2' '2']
 ['2' '2' '2']]


In [178]:
f2.shape

(2, 3)

In [183]:
f4=np.full([2,3,4],'going good')
print(f4)

[[['going good' 'going good' 'going good' 'going good']
  ['going good' 'going good' 'going good' 'going good']
  ['going good' 'going good' 'going good' 'going good']]

 [['going good' 'going good' 'going good' 'going good']
  ['going good' 'going good' 'going good' 'going good']
  ['going good' 'going good' 'going good' 'going good']]]


In [186]:
np.ndim(f4)



3

# Random function

Random module has fnc which are used for generating random numbers

In [191]:
import numpy as np

In [193]:
from numpy import random

In [195]:
np.random.random()

0.2153858989775762

In [197]:
np.random.random(3)

array([0.53448326, 0.4541837 , 0.65930696])

In [199]:
np.random.random((2,4))

array([[0.15160935, 0.25693351, 0.69847504, 0.40900695],
       [0.5431503 , 0.91438537, 0.72961769, 0.10702301]])

In [201]:
np.random.random((4,4,6))

array([[[0.70573488, 0.0351639 , 0.70701076, 0.93634361, 0.00377536,
         0.77769066],
        [0.8870046 , 0.72244392, 0.32221353, 0.23195049, 0.6138454 ,
         0.74450244],
        [0.45925799, 0.02002213, 0.63143797, 0.71619885, 0.67878159,
         0.99693974],
        [0.46637173, 0.15841378, 0.77628741, 0.67254749, 0.60100494,
         0.12843437]],

       [[0.54884526, 0.10105557, 0.51819561, 0.79061946, 0.30726731,
         0.30215265],
        [0.20800871, 0.59630294, 0.24646361, 0.88252824, 0.47161143,
         0.08418644],
        [0.96786837, 0.88216546, 0.2548952 , 0.5731409 , 0.23342671,
         0.18210652],
        [0.90651376, 0.50350238, 0.29210199, 0.6354145 , 0.48804364,
         0.98742866]],

       [[0.89078813, 0.89648271, 0.91841562, 0.56621861, 0.37840838,
         0.8177084 ],
        [0.6587182 , 0.84130888, 0.81016825, 0.4727001 , 0.63885996,
         0.53381072],
        [0.90727805, 0.43576784, 0.64889565, 0.16879656, 0.25137682,
         0.091647

In [203]:
np.random.randint(1,45)

22

In [213]:
np.random.randint(3,13,6)

array([6, 4, 5, 7, 5, 4])

In [217]:
np.random.randint(5)

4

In [219]:
np.random.rand()

0.3554983089900784

In [221]:
np.random.rand(5)

array([0.95724103, 0.49006578, 0.95858227, 0.3320312 , 0.23656991])

In [223]:
np.random.rand(2,9)

array([[0.69304519, 0.49308031, 0.57521266, 0.03949066, 0.8574756 ,
        0.8112926 , 0.31016038, 0.22844521, 0.25348165],
       [0.47046381, 0.46646679, 0.57237593, 0.30069112, 0.97949178,
        0.63764344, 0.64927751, 0.4111517 , 0.07274976]])

In [229]:
np.random.rand(3,44,16)

array([[[0.91938771, 0.14271469, 0.34647307, ..., 0.38282271,
         0.24141266, 0.7072002 ],
        [0.80880982, 0.98602382, 0.12716627, ..., 0.19366709,
         0.5770167 , 0.4351781 ],
        [0.55946752, 0.73118214, 0.41524366, ..., 0.39257459,
         0.7409753 , 0.68665249],
        ...,
        [0.11425374, 0.4167172 , 0.7521613 , ..., 0.02719238,
         0.2458724 , 0.75836066],
        [0.79049561, 0.97212135, 0.10243492, ..., 0.08511172,
         0.30954126, 0.17785911],
        [0.79492668, 0.72732537, 0.99689656, ..., 0.8308583 ,
         0.48064967, 0.01544647]],

       [[0.8728069 , 0.77903801, 0.39061737, ..., 0.73539875,
         0.66074852, 0.87050637],
        [0.24266938, 0.246365  , 0.965347  , ..., 0.19692305,
         0.41066873, 0.117715  ],
        [0.81733426, 0.51016601, 0.07390099, ..., 0.67589173,
         0.77778657, 0.39830923],
        ...,
        [0.0038975 , 0.3703887 , 0.71861795, ..., 0.49277578,
         0.88106399, 0.28207072],
        [0.3

In [235]:
np.random.randn()

1.7584395662605876

In [237]:
np.random.randn(4)

array([ 1.23537907,  1.48345204, -0.05462905, -0.87380063])

In [239]:
np.random.randn(3,45)

array([[-0.18933741, -0.38433344,  0.93802423, -0.26961155, -0.24816889,
         0.36530105, -0.65064275, -0.85727007,  1.03656707, -0.89899116,
         0.07935748,  0.09497372,  0.56582494, -0.55185092,  0.62607329,
        -0.90684149, -1.01429669,  1.4779728 , -0.06633909,  0.16490961,
        -0.58059754,  0.29619703,  0.48798626, -0.26059735,  0.98304459,
        -0.17740414,  1.55728389,  1.28296685, -0.80177446, -1.51688917,
        -0.80115333, -1.51135275, -1.48536872, -1.15386953,  0.75152547,
         0.349386  ,  1.17097723, -1.08262227, -0.24717552,  2.00112478,
         2.01756528,  0.59279607,  0.57455497,  0.86163024, -0.48213788],
       [-0.62061436,  0.05665766,  1.66421149, -2.1321705 , -0.66201735,
        -1.50156681,  2.35691039,  0.7900249 , -0.78073461,  0.09109267,
         0.38523142,  0.44756286,  0.3122657 , -0.14946782, -0.64005448,
        -0.31830203,  0.98167771,  0.71063952,  1.17987484,  1.24745876,
        -0.73329938, -0.38147104, -0.01581634, -1.

In [245]:
np.random.randn(4,5,6)

array([[[-1.42143376, -1.27924142,  0.64930301,  0.90368041,
         -1.83805138,  0.5803255 ],
        [-0.88087427,  1.37426157, -0.57847574,  1.0777527 ,
         -1.01354471, -1.16480757],
        [ 0.29349603, -0.09909918, -1.27066281,  1.11638275,
         -1.39206867,  1.02977684],
        [ 0.52820604, -0.80844544,  1.51339714,  0.93341689,
         -0.55514234, -0.97359068],
        [ 0.64529807,  0.79075464,  1.27439586,  1.32731617,
         -0.75057856, -0.10202666]],

       [[-0.10831787, -0.35118466,  0.71418662, -0.54202584,
         -0.08936866, -0.88815821],
        [ 0.12624798,  0.30660574,  0.38819758,  0.34430023,
         -1.64408935,  0.50260921],
        [-2.06676232, -0.27334059,  2.15607283, -2.04302329,
         -0.61689091, -0.2670295 ],
        [-0.39141379, -0.29173642, -0.89294373, -1.81384973,
         -0.04129157,  1.05376677],
        [-0.59602446,  0.20922921, -0.87831405,  0.7644558 ,
          1.74026216, -1.08105579]],

       [[-0.27430833,  0.9

In [247]:
np.random.uniform(2,4)

2.9741902657449826

In [251]:
np.random.uniform(3,5,7)

array([4.88902196, 3.88255059, 3.06658897, 3.56263008, 3.32498438,
       4.31268772, 3.10904263])

In [255]:
np.random.uniform(3)

2.1560533735803955

In [259]:
np.random.uniform()

0.15222519173252558

In [263]:
np.random.choice([2,4,6,8,10,12,14,16,18,20])

6

In [269]:
np.random.choice([2,4,6,8,10,12,14,16,18,20],4)

array([12, 16,  8, 20])

In [271]:
np.random.choice(13,133)

array([12,  5,  8, 12, 12,  1,  4,  0,  1,  4,  1,  2, 12,  5,  9,  5,  0,
        7,  6,  9,  8,  6,  1,  9,  2,  3,  4,  9,  2,  2,  1,  7,  8,  2,
        7,  3,  5,  8, 10, 12,  3,  8,  2,  7, 11, 12,  4,  5,  7,  9, 12,
        9,  6,  1,  7,  0,  0,  1,  8,  8,  0,  6,  8,  4,  4,  3,  6,  9,
       11, 10,  4,  3,  4,  8,  9,  4, 12,  8,  9,  7,  6,  7,  8,  5,  0,
        3,  3,  6,  5, 10, 10,  8,  2,  0, 12,  3, 11, 10,  7,  4,  2, 10,
        1,  9,  4,  9,  2,  5, 10,  1,  5,  7,  1,  8,  7,  3,  0,  9, 12,
        1,  3,  1,  6,  0, 10,  3,  8,  6,  1,  6, 11,  1, 10])

In [275]:
np.random.choice(29)

7

In [283]:

np.random.choice([2,4,6,8,10,12,14,16,18,20],size=40,replace=True)

array([14, 10, 10, 18, 12,  2, 20,  4, 14,  6, 18,  6,  4,  6,  8, 10,  6,
        2, 10, 10,  2, 10, 18, 10,  2, 16,  4,  6, 14, 12, 14, 14,  2, 14,
       12,  4,  4, 14,  8, 16])

In [285]:
np.random.choice([2,4,6,8,10,12,14,16,18,20],size=4,replace=False)

array([16,  4,  8,  2])

# Linspace function

returns evenly spaced values in a given interval

by default it shows 50 values

In [288]:
import numpy as np

In [326]:
A=np.linspace(2,30,num=11,retstep=True)

In [328]:
print(A)

(array([ 2. ,  4.8,  7.6, 10.4, 13.2, 16. , 18.8, 21.6, 24.4, 27.2, 30. ]), 2.8)


In [296]:
np.linspace(2,34,num=13,endpoint=False)
print(A)

[ 2.   4.8  7.6 10.4 13.2 16.  18.8 21.6 24.4 27.2 30. ]


In [300]:
A=np.linspace(2,34,num=12,endpoint=True)
print(A)

[ 2.          4.90909091  7.81818182 10.72727273 13.63636364 16.54545455
 19.45454545 22.36363636 25.27272727 28.18181818 31.09090909 34.        ]


In [308]:
A=np.linspace(2,34,num=12,endpoint=False)
print(A)

[ 2.          4.66666667  7.33333333 10.         12.66666667 15.33333333
 18.         20.66666667 23.33333333 26.         28.66666667 31.33333333]


In [312]:
A=np.linspace(2,34,num=12,endpoint=True,dtype=int)
print(A)

[ 2  4  7 10 13 16 19 22 25 28 31 34]


In [334]:
A=np.linspace(2,34,num=12,endpoint=True,dtype=str,retstep=False)
print(A)

['2.0' '4.909090909090909' '7.818181818181818' '10.727272727272727'
 '13.636363636363637' '16.545454545454547' '19.454545454545453'
 '22.363636363636363' '25.272727272727273' '28.181818181818183'
 '31.090909090909093' '34.0']


In [336]:
A=np.linspace(2,34,num=45,retstep=True)
print(A)

(array([ 2.        ,  2.72727273,  3.45454545,  4.18181818,  4.90909091,
        5.63636364,  6.36363636,  7.09090909,  7.81818182,  8.54545455,
        9.27272727, 10.        , 10.72727273, 11.45454545, 12.18181818,
       12.90909091, 13.63636364, 14.36363636, 15.09090909, 15.81818182,
       16.54545455, 17.27272727, 18.        , 18.72727273, 19.45454545,
       20.18181818, 20.90909091, 21.63636364, 22.36363636, 23.09090909,
       23.81818182, 24.54545455, 25.27272727, 26.        , 26.72727273,
       27.45454545, 28.18181818, 28.90909091, 29.63636364, 30.36363636,
       31.09090909, 31.81818182, 32.54545455, 33.27272727, 34.        ]), 0.7272727272727273)


# Empty Function

used to create an array of arbitrary values of given shape and datatype without initializing the entries

In [339]:
import numpy as np

In [341]:
a=np.empty(4)

In [343]:
print(a)

[1.23537907 1.48345204 0.05462905 0.87380063]


In [345]:
a=np.empty(4,dtype=int)
print(a)

[-1481273904         139           0           0]


In [349]:
a=np.empty(6,dtype=object)

In [353]:
a

array([None, None, None, None, None, None], dtype=object)

In [355]:
c=np.empty((5,2))

In [357]:
c

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 1.24610994e-306],
       [1.42413555e-306, 1.78019082e-306],
       [1.37959740e-306, 6.23057349e-307],
       [1.42419530e-306, 4.42622108e-315]])

In [367]:
b=np.empty((3,5),dtype=int)
b

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [369]:
b=np.empty((3,5),dtype=str)
b

array([['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', '']], dtype='<U1')

In [371]:
b=np.empty((5,11),dtype=object)
b

array([[None, None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None, None]],
      dtype=object)

In [373]:
a=np.empty([3,5,8])
a

array([[[1.42143376, 1.27924142, 0.64930301, 0.90368041, 1.83805138,
         0.5803255 , 0.88087427, 1.37426157],
        [0.57847574, 1.0777527 , 1.01354471, 1.16480757, 0.29349603,
         0.09909918, 1.27066281, 1.11638275],
        [1.39206867, 1.02977684, 0.52820604, 0.80844544, 1.51339714,
         0.93341689, 0.55514234, 0.97359068],
        [0.64529807, 0.79075464, 1.27439586, 1.32731617, 0.75057856,
         0.10202666, 0.10831787, 0.35118466],
        [0.71418662, 0.54202584, 0.08936866, 0.88815821, 0.12624798,
         0.30660574, 0.38819758, 0.34430023]],

       [[1.64408935, 0.50260921, 2.06676232, 0.27334059, 2.15607283,
         2.04302329, 0.61689091, 0.2670295 ],
        [0.39141379, 0.29173642, 0.89294373, 1.81384973, 0.04129157,
         1.05376677, 0.59602446, 0.20922921],
        [0.87831405, 0.7644558 , 1.74026216, 1.08105579, 0.27430833,
         0.92908193, 0.29896844, 0.150836  ],
        [0.8152251 , 0.42789367, 0.24076503, 0.95286432, 0.33466931,
         

In [377]:
a=np.empty([2,4,6],dtype=int)

In [381]:
a

array([[[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]])

In [385]:
a=np.empty([2,4,6],dtype=object)
print(a)

[[[None None None None None None]
  [None None None None None None]
  [None None None None None None]
  [None None None None None None]]

 [[None None None None None None]
  [None None None None None None]
  [None None None None None None]
  [None None None None None None]]]


# Eye function

returns a 2-D array with 1 on diagnonal and 0 elsewhere

In [388]:
A=np.eye(23)
A

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0.,

In [390]:
A=np.eye(2,k=0)
A

array([[1., 0.],
       [0., 1.]])

In [392]:
A=np.eye(5,k=1)
A

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [394]:
A=np.eye(3,k=-1)
A

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [396]:
A=np.eye(4,dtype=int)
A

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [398]:
A=np.eye(5,7)
A

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]])

In [400]:
A=np.eye(2,7)
A

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.]])

In [402]:
np.eye(1)

array([[1.]])

In [404]:
np.eye(13)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [408]:
np.eye(3,7,k=5,dtype=int)

array([[0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0]])

In [410]:
np.eye(5,dtype=str)

array([['1', '', '', '', ''],
       ['', '1', '', '', ''],
       ['', '', '1', '', ''],
       ['', '', '', '1', ''],
       ['', '', '', '', '1']], dtype='<U1')

In [414]:
np.ndim(A)

2

# Identity Function

returns an identity ie a square with 1 on the main diagonal and all other are 0

In [419]:
A=np.identity(23)
A

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0.,

In [421]:
np.identity(5,dtype=int)


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [423]:
A.ndim

2

In [427]:

A.size

529

In [429]:
A.shape

(23, 23)

In [431]:
A

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0.,

In [433]:
A*23

array([[23.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., 23.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 23.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 23.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 23.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 23.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., 23.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., 23.,  0.,  0.,  0.,  0.,  0.,
   

In [435]:
A*8.9

array([[8.9, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 8.9, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 8.9, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 8.9, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 8.9, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 8.9, 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 8.9, 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 8.9, 0. , 0. , 0. , 0. , 0. ,
   

# Zeros like Ones like Full like Arrays

In [438]:
import numpy as np

In [440]:
from numpy import random

In [442]:
A=np.array([21,34,56])
A

array([21, 34, 56])

In [444]:
B=np.ones_like(A)
B

array([1, 1, 1])

In [448]:
C=np.random.random((3,5))
C

array([[0.26294042, 0.42028676, 0.67477529, 0.01675747, 0.35622684],
       [0.7821213 , 0.17179522, 0.41994632, 0.91915037, 0.53581818],
       [0.2290344 , 0.29717224, 0.86795723, 0.54565697, 0.37798489]])

In [450]:
D=np.ones_like((C))
D

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [452]:
D=np.ones_like(C,dtype=int)
D

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [454]:
A

array([21, 34, 56])

In [456]:
B=np.zeros_like(A)
B

array([0, 0, 0])

In [460]:
A=np.random.randn(2,5)
A

array([[ 0.64653506, -0.63659567, -0.80055581, -0.16844438, -0.32496626],
       [ 0.85388509, -0.89085054, -0.79776767, -0.36765689,  0.15343049]])

In [462]:
A=np.zeros_like(B)
A

array([0, 0, 0])

In [464]:
A=np.zeros_like(C,dtype=int)
A

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [466]:
A


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [468]:
B=np.full_like(A,6)
B

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [470]:
B=random.randn(2,5,7)
B

array([[[ 0.92645915, -0.86258925, -1.29263185,  0.46796194,
         -0.61798019,  0.08857495, -1.00487752],
        [-1.3127771 ,  0.34085766, -1.1485639 ,  0.48976108,
          0.83156959, -0.95407167,  0.46445145],
        [ 0.68414008,  0.30156658,  1.06720062,  0.7162328 ,
          0.64374761,  1.56421949, -2.36327223],
        [ 1.27858331, -0.32894779,  1.06973407,  0.55794218,
          1.05106277,  0.43123433, -0.66597614],
        [-1.14449026, -0.24903118,  0.12381912, -2.24499993,
         -0.58588998, -0.81844811, -1.55299251]],

       [[-2.75309803, -1.21080059,  1.26759013, -1.57903395,
         -0.26717357, -2.3613819 ,  0.03626646],
        [-0.51193651,  1.45928901, -0.09273353,  0.09950586,
          1.72004668,  0.36717829, -0.09879923],
        [ 0.98493791, -0.25972309, -0.49466537,  0.4451837 ,
         -0.21738862, -0.31991629, -1.41084037],
        [ 0.12986677,  1.7069437 , -1.24035949,  1.01286047,
         -0.52509871,  0.78504129, -2.06141489],
        

In [472]:
B=np.full_like(A,34)
B

array([[34, 34, 34, 34, 34],
       [34, 34, 34, 34, 34],
       [34, 34, 34, 34, 34]])

In [474]:
A=np.full_like(B,-89,int)
A

array([[-89, -89, -89, -89, -89],
       [-89, -89, -89, -89, -89],
       [-89, -89, -89, -89, -89]])

# Diagonal Array Functions

In [479]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [481]:
A.ndim

2

In [483]:
np.diag(A)

array([1, 5, 9])

In [485]:
H=np.array([1,2,3,4,5,6,7,8,9,])
H

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [487]:
H.ndim

1

In [489]:
np.diag(H)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [491]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [493]:
np.diag(A,k=0)

array([1, 5, 9])

In [495]:
np.diag(A,k=1)

array([2, 6])

In [497]:
np.diag(A,k=3)

array([], dtype=int32)

In [505]:
np.diag(A,k=-2)

array([7])

In [509]:
H=np.array([1,2,3,4,5,6,7,8,9,])
np.diag(H,k=0)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [511]:
np.diag(H,k=2)

array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# Transpose function

In [516]:
A=np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [518]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [520]:
A.shape

(2, 3)

In [524]:
A.T.shape

(3, 2)

In [526]:
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [528]:
I=np.array ([11,12,34,45,56])
I

I.T

array([11, 12, 34, 45, 56])

In [530]:
A=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
A

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [532]:
A.T

array([[[1],
        [4],
        [7]],

       [[2],
        [5],
        [8]],

       [[3],
        [6],
        [9]]])

In [534]:
A.shape

(1, 3, 3)

In [536]:
A.T.shape

(3, 3, 1)

# Unary Operations

In [539]:
A=np.array([1,34,56,78])
A


array([ 1, 34, 56, 78])

In [541]:
A.max()
A.min()
A.sum()


169

In [543]:
E=np.array([[1,23,45],[56,3,4]])
E

array([[ 1, 23, 45],
       [56,  3,  4]])

In [545]:
E.max()

56

In [547]:
E.min()

1

In [549]:
E.sum()

132

In [551]:
E.max(axis=1)

array([45, 56])

In [555]:
E.max(axis=0)

array([56, 23, 45])

In [557]:

E.sum(axis=1)

array([69, 63])

In [559]:
E.sum(axis=0)

array([57, 26, 49])

In [567]:
Y=np.arange(18).reshape(2,3,3)
Y

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [569]:
Y.max()

17

In [571]:
Y.min()

0

In [573]:
Y.max(axis=1)

array([[ 6,  7,  8],
       [15, 16, 17]])

In [575]:
Y.min(axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [577]:
Y.min(axis=1)

array([[ 0,  1,  2],
       [ 9, 10, 11]])

In [579]:
Y.sum()

153

In [581]:
Y.sum(axis=0)

array([[ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [583]:
Y.sum(axis=1)

array([[ 9, 12, 15],
       [36, 39, 42]])

# V stack  and H stack

In [588]:
A=np.array(3)
B=np.array(3)

np.vstack((A,B))

array([[3],
       [3]])

In [592]:

np.hstack((A,B))

array([3, 3])

In [594]:
E=np.array([[1,23,45],[56,3,4]])
E

array([[ 1, 23, 45],
       [56,  3,  4]])

In [596]:
F=np.array([[11,3,55],[5,38,74]])
F

array([[11,  3, 55],
       [ 5, 38, 74]])

In [600]:
V2=np.vstack((E,F))
V2

array([[ 1, 23, 45],
       [56,  3,  4],
       [11,  3, 55],
       [ 5, 38, 74]])

In [602]:
H2=np.hstack((E,F))
H2

array([[ 1, 23, 45, 11,  3, 55],
       [56,  3,  4,  5, 38, 74]])

# Array indexing

In [607]:
A=np.array([1,2,3,4,5,6,7,8,9,10])
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [609]:
A[0]

1

In [611]:
A[1:6]

array([2, 3, 4, 5, 6])

In [613]:
A[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [615]:
A[0:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [617]:
A[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [619]:
A[2:3:2]

array([3])

In [621]:
E=np.array([[1,23,45],[56,3,4]])
E

array([[ 1, 23, 45],
       [56,  3,  4]])

In [623]:
E[:]

array([[ 1, 23, 45],
       [56,  3,  4]])

In [625]:
E[1:5]

array([[56,  3,  4]])

In [627]:
E[1:2:2]

array([[56,  3,  4]])

In [629]:
E[0:]

array([[ 1, 23, 45],
       [56,  3,  4]])

# Any and All functions

In [632]:
x=np.random.randint(10,1001,12)

In [634]:
x

array([862, 507, 641, 106, 361, 677, 618, 578, 934, 318, 640, 321])

In [638]:
np.any(x==343)

False

In [640]:
np.any(x>201)

True

In [642]:
np.any(x<1)

False

In [644]:
np.all(x==500)

False

In [646]:
np.all(x<1001)

True

In [648]:
np.all(x>1001)

False

In [650]:
np.all(x<1)

False